#!/usr/bin/env python3
"""
Add Source links to changelog markdown files.

This script processes a changelog file generated by Claude and adds [[Source](url)]
links with proper anchors by reading the actual source files.

Usage:
    uv run add_source_anchors.py changelogs/2026/01/changelog-2026-01-24.md
"""
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///

import re
import sys
from pathlib import Path


# URL mapping for source links
URL_MAPPINGS = {
    "docs-md/claude-code/": "https://code.claude.com/docs/en/",
    "docs-md/api/": "https://platform.claude.com/docs/en/",
}

# Pattern to find document header: #### [Name](github-url-to-docs-md)
# Captures: (full link part), (file path after docs-md/)
HEADER_PATTERN = re.compile(
    r"^(####\s+\[[^\]]+\]\(https://github\.com/[^)]+/docs-md/([^)]+\.md)\))"
)

# Pattern to find line reference in a bullet: [[line N](github-url)] or [[lines N-M](github-url)]
# Captures: (start line number), (file path after docs-md/)
LINE_REF_PATTERN = re.compile(
    r"\[\[lines?\s+(\d+)(?:-\d+)?\]\(https://github\.com/[^)]+/docs-md/([^)]+\.md)\?plain=1#L\d+[^\]]*\)\]"
)

# Pattern to check if line already has a Source link
HAS_SOURCE_PATTERN = re.compile(r"\[\[Source\]\([^)]+\)\]")

# Match anchor in markdown: [​](#anchor-name) - with optional zero-width space
ANCHOR_PATTERN = re.compile(r"\[[\u200b]?\]\(#([^)]+)\)")


def map_to_source_url(file_path: str) -> str | None:
    """Map a local docs-md path to its source URL."""
    for prefix, base_url in URL_MAPPINGS.items():
        if file_path.startswith(prefix):
            # Remove prefix and .md extension
            path = file_path[len(prefix) :]
            if path.endswith(".md"):
                path = path[:-3]
            return base_url + path
    return None


def find_anchor_above_line(file_path: Path, target_line: int) -> str | None:
    """Find the closest anchor above the target line in the file."""
    if not file_path.exists():
        print(f"  Warning: File not found: {file_path}")
        return None

    if target_line < 1:
        print(f"  Warning: Invalid line number: {target_line}")
        return None

    try:
        content = file_path.read_text(encoding="utf-8")
    except UnicodeDecodeError as e:
        print(f"  Warning: Encoding error reading {file_path}: {e}")
        return None

    lines = content.split("\n")

    # Search backwards from target line to find the nearest anchor
    for line_num in range(min(target_line - 1, len(lines) - 1), -1, -1):
        line = lines[line_num]
        match = ANCHOR_PATTERN.search(line)
        if match:
            return match.group(1)

    return None


def process_line(line: str) -> str:
    """Process a single line and add Source links if needed."""
    # Skip if already has a Source link
    if HAS_SOURCE_PATTERN.search(line):
        return line

    # Check for document header
    header_match = HEADER_PATTERN.match(line)
    if header_match:
        full_link = header_match.group(1)
        file_path = header_match.group(2)
        source_url = map_to_source_url(f"docs-md/{file_path}")

        if source_url:
            # Add Source link after the header link
            new_line = line.replace(full_link, f"{full_link} [[Source]({source_url})]")
            print(f"  Added Source to header: {file_path}")
            return new_line
        return line

    # Check for bullet with line reference
    if line.strip().startswith("*"):
        line_ref_match = LINE_REF_PATTERN.search(line)
        if line_ref_match:
            line_num = int(line_ref_match.group(1))
            file_path = line_ref_match.group(2)
            local_path = Path("docs-md") / file_path
            source_url = map_to_source_url(f"docs-md/{file_path}")

            if source_url:
                # Find anchor above the referenced line
                anchor = find_anchor_above_line(local_path, line_num)
                if anchor:
                    source_with_anchor = f"{source_url}#{anchor}"
                    print(f"  Added Source #{anchor} for line {line_num} in {file_path}")
                else:
                    source_with_anchor = source_url
                    print(f"  Added Source (no anchor) for line {line_num} in {file_path}")

                # Append Source link at the end of the line
                return f"{line} [[Source]({source_with_anchor})]"

    return line


def process_changelog(changelog_path: Path) -> str:
    """Process a changelog file and add Source links."""
    content = changelog_path.read_text(encoding="utf-8")
    lines = content.split("\n")
    result_lines = [process_line(line) for line in lines]
    return "\n".join(result_lines)


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <changelog-file>")
        return 1

    changelog_path = Path(sys.argv[1])
    if not changelog_path.exists():
        print(f"Error: File not found: {changelog_path}")
        return 1

    print(f"Processing: {changelog_path}")

    # Process the changelog
    updated_content = process_changelog(changelog_path)

    # Write back
    changelog_path.write_text(updated_content, encoding="utf-8")
    print(f"\nUpdated: {changelog_path}")

    print("\nDone!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
